### ISSUE TITLE
Google doc for "Notify me" still talks about the Alpha

### ISSUE THREAD

**Issue by realvictorprm** [andrewpey/vtland#23]
Hey folks,

the Google Doc for Notify me still talks about the Alpha (yeah as the title says) although we are already in Beta if I understood things correctly?
![image](https://user-images.githubusercontent.com/25414896/118031411-c8b0d400-b366-11eb-98df-c4c6cc183d2b.png)

You might want to consider updating this (would have done myself if it would be possible :D).

Cheers and thanks for the nice game!

**Comment by andrewpey** [comment]
Nice catch, thanks!
