### ISSUE TITLE
Раздел FAQ (RU)

### ISSUE THREAD

**Issue by aLegoz** [andrewpey/vtland#5]
Предложение изменить раздел FAQ и поделить вопросы на категории и спрятать ответы под спойлеры для более удобного чтения и просмотра страницы. 
![Пример](http://training.vimm.com/wp-content/uploads/FAQ-sample-on-page.jpg)

**Comment by andrewpey** [comment]
Done in df67bf039e5ad8c52b813a8b8fd82788bfe7b8c5
